project_id = "sddoxjootttbluiqzsag"

[functions.expand-content]
verify_jwt = false

[functions.export-product]
verify_jwt = false

[functions.generate-kdp-metadata]
verify_jwt = false

[functions.generate-sales-page]
verify_jwt = false

[functions.generate-launch-assets]
verify_jwt = false

[functions.copilot-chat]
verify_jwt = false

[functions.verify-api-key]
verify_jwt = false

[functions.ai-edit-content]
verify_jwt = false

[functions.auto-layout-ebook]
verify_jwt = false
